# Generated by Django 4.2 on 2023-05-30 17:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_gastos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('detail', models.TextField(blank=True, max_length=250, null=True)),
                ('percentage', models.FloatField(blank=True, default=0, max_length=3, null=True)),
                ('last_funds', models.FloatField(default=0, max_length=15)),
                ('current_funds', models.FloatField(default=0, max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Movements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(max_length=15)),
                ('savings', models.FloatField(default=0, max_length=15)),
                ('total_amount', models.FloatField(default=0, max_length=15)),
                ('salary_funds_before', models.FloatField(default=0, max_length=15)),
                ('salary_funds_after', models.FloatField(default=0, max_length=15)),
                ('savings_funds_before', models.FloatField(default=0, max_length=15)),
                ('savings_funds_after', models.FloatField(max_length=15)),
                ('date', models.DateField(default=datetime.date.today)),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('detail', models.TextField(blank=True, max_length=15, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor_gastos.category')),
            ],
        ),
        migrations.DeleteModel(
            name='contact',
        ),
    ]
