# Generated by Django 4.2 on 2023-05-30 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_gastos', '0002_category_movements_delete_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='goal_founds',
            field=models.FloatField(default=0, max_length=15),
        ),
        migrations.AlterField(
            model_name='movements',
            name='savings_funds_after',
            field=models.FloatField(default=0, max_length=15),
        ),
    ]
