# Generated by Django 4.2 on 2023-05-30 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_gastos', '0003_category_goal_founds_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='goal_founds',
            field=models.FloatField(blank=True, default=0, max_length=15, null=True),
        ),
    ]
