# Generated by Django 4.2 on 2023-05-31 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_gastos', '0004_alter_category_goal_founds'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_payment',
            field=models.BooleanField(default=True),
        ),
    ]
