# Generated by Django 4.2 on 2023-05-31 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_gastos', '0006_movements_still_exist'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='still_exist',
            field=models.BooleanField(default=True),
        ),
    ]
