# Generated by Django 4.2 on 2023-06-01 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_gastos', '0007_category_still_exist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movements',
            name='detail',
            field=models.TextField(blank=True, default='-', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='movements',
            name='payment_method',
            field=models.CharField(blank=True, default='-', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='movements',
            name='total_amount',
            field=models.FloatField(max_length=15),
        ),
    ]
