# Generated by Django 4.2 on 2023-06-01 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_gastos', '0010_movements_is_savings_withdraw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movements',
            name='payment_method',
            field=models.CharField(blank=True, default='-', max_length=200, null=True),
        ),
    ]
