# Generated by Django 4.2 on 2023-06-03 04:46

import datetime
from django.db import migrations, models

def actualizar_fecha_hora(apps, schema_editor):
    TuModelo = apps.get_model('gestor_gastos', 'Movements')

    for obj in TuModelo.objects.all():
        fecha_hora_str = obj.date
        
        obj.date = fecha_hora_str

class Migration(migrations.Migration):

    dependencies = [
        ('gestor_gastos', '0016_alter_movements_date'),
    ]

    operations = [
        migrations.RunPython(actualizar_fecha_hora),
        migrations.AlterField(
            model_name='movements',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 3, 4, 46, 14, 549923, tzinfo=datetime.timezone.utc)),
        ),
    ]
