# Generated by Django 4.2 on 2023-06-04 15:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_gastos', '0017_alter_movements_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movements',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 4, 15, 9, 35, 413280, tzinfo=datetime.timezone.utc)),
        ),
    ]
