# Generated by Django 4.2 on 2023-07-06 00:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_gastos', '0018_alter_movements_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movements',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 6, 0, 37, 54, 92056, tzinfo=datetime.timezone.utc)),
        ),
    ]
