# Generated by Django 4.2 on 2023-07-10 23:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_gastos', '0019_alter_movements_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movements',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 10, 23, 4, 27, 522358, tzinfo=datetime.timezone.utc)),
        ),
    ]
